// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcyzqxpbolpxcjnwpgio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjeXpxeHBib2xweGNqbndwZ2lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjA1NzEsImV4cCI6MjA2ODczNjU3MX0.j5mMry6oH52xnndR820ZL8LMe01_QGlhA0kbrQo__iE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});